// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for posts documents */
interface PostsDocumentData {
    /**
     * Slice Zone field in *posts*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: posts.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PostsDocumentDataSlicesSlice>;
}
/**
 * Slice for *posts → Slice Zone*
 *
 */
type PostsDocumentDataSlicesSlice = HeaderPostSlice | MainPostSlice | AdditionalContentSlice;
/**
 * posts document from Prismic
 *
 * - **API ID**: `posts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PostsDocumentData>, "posts", Lang>;
export type AllDocumentTypes = PostsDocument;
/**
 * Primary content in AdditionalContent → Primary
 *
 */
interface AdditionalContentSliceDefaultPrimary {
    /**
     * image field in *AdditionalContent → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: additional_content.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * description field in *AdditionalContent → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: additional_content.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for AdditionalContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: `AdditionalContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AdditionalContentSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<AdditionalContentSliceDefaultPrimary>, never>;
/**
 * Slice variation for *AdditionalContent*
 *
 */
type AdditionalContentSliceVariation = AdditionalContentSliceDefault;
/**
 * AdditionalContent Shared Slice
 *
 * - **API ID**: `additional_content`
 * - **Description**: `AdditionalContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AdditionalContentSlice = prismicT.SharedSlice<"additional_content", AdditionalContentSliceVariation>;
/**
 * Primary content in HeaderPost → Primary
 *
 */
interface HeaderPostSliceDefaultPrimary {
    /**
     * Title field in *HeaderPost → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: header_post.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * sub_title field in *HeaderPost → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: header_post.primary.sub_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    sub_title: prismicT.TitleField;
    /**
     * author field in *HeaderPost → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: header_post.primary.author
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    author: prismicT.RichTextField;
}
/**
 * Default variation for HeaderPost Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeaderPost`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderPostSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeaderPostSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HeaderPost*
 *
 */
type HeaderPostSliceVariation = HeaderPostSliceDefault;
/**
 * HeaderPost Shared Slice
 *
 * - **API ID**: `header_post`
 * - **Description**: `HeaderPost`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderPostSlice = prismicT.SharedSlice<"header_post", HeaderPostSliceVariation>;
/**
 * Primary content in MainPost → Primary
 *
 */
interface MainPostSliceDefaultPrimary {
    /**
     * main field in *MainPost → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: main_post.primary.main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    main: prismicT.RichTextField;
}
/**
 * Item in MainPost → Items
 *
 */
export interface MainPostSliceDefaultItem {
    /**
     * content_repeatable field in *MainPost → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: main_post.items[].content_repeatable
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content_repeatable: prismicT.RichTextField;
    /**
     * code field in *MainPost → Items*
     *
     * - **Field Type**: Embed
     * - **Placeholder**: *None*
     * - **API ID Path**: main_post.items[].code
     * - **Documentation**: https://prismic.io/docs/core-concepts/embed
     *
     */
    code: prismicT.EmbedField;
}
/**
 * Default variation for MainPost Slice
 *
 * - **API ID**: `default`
 * - **Description**: `MainPost`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MainPostSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<MainPostSliceDefaultPrimary>, Simplify<MainPostSliceDefaultItem>>;
/**
 * Slice variation for *MainPost*
 *
 */
type MainPostSliceVariation = MainPostSliceDefault;
/**
 * MainPost Shared Slice
 *
 * - **API ID**: `main_post`
 * - **Description**: `MainPost`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type MainPostSlice = prismicT.SharedSlice<"main_post", MainPostSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { PostsDocumentData, PostsDocumentDataSlicesSlice, PostsDocument, AllDocumentTypes, AdditionalContentSliceDefaultPrimary, AdditionalContentSliceDefault, AdditionalContentSliceVariation, AdditionalContentSlice, HeaderPostSliceDefaultPrimary, HeaderPostSliceDefault, HeaderPostSliceVariation, HeaderPostSlice, MainPostSliceDefaultPrimary, MainPostSliceDefaultItem, MainPostSliceDefault, MainPostSliceVariation, MainPostSlice };
    }
}
